#!/usr/bin/env python3
# =============================================================================
# @file    create-pyz
# @brief   Script to create eprints2archives executable zipapps using shiv
# @created 2021-07-19
# @license Please see the file named LICENSE in the project directory
# @website https://github.com/caltechlibrary/eprints2archives
#
# Preliminary setup assumed to have been done before this is run:
#
# MacOS:
#   brew install python@3.6
#   brew install python@3.7
#   brew install python@3.8
#   brew install python@3.9
#   brew install pyenv
#   pyenv install 3.6.11
#   pyenv install 3.7.10
#   pyenv install 3.8.10
#   pyenv install 3.9.5
#
# Ubuntu 18:
#   apt install curl wget git llvm build-essential libssl-dev 
#   apt install libsqlite3-dev xz-utils tk-dev libffi-dev liblzma-dev
#   apt install zlib1g-dev libbz2-dev libreadline-dev 
#   apt install libncurses5-dev libncursesw5-dev
#   curl https://pyenv.run | bash
#   pyenv install 3.6.11
#   pyenv install 3.7.10
#   pyenv install 3.8.10
#   pyenv install 3.9.5
# =============================================================================

from   datetime import date
from   fastnumbers import isint
import pkg_resources
from   os import getcwd, chdir, system
from   os.path import exists, dirname, join, basename
from   rich.console import Console
import subprocess
from   subprocess import check_output, check_call
import sys
from   sys import exit
import zipfile
from   zipfile import ZipFile, ZIP_STORED, ZIP_DEFLATED


# Constants used later.
# .............................................................................

# macOS Catalina (and probably later) systems ship with a /usr/bin/python3,
# but NOT a /usr/bin/python3.8.  The initial /usr/bin/python3 is a stub that
# offers to download and install Python the first time you run it.  What it
# installs still does not have an executable named "python3.8", only python3.
# Thus, we can't ask for an explicit x.y version of Python in the hash-bang
# line because that would always fail on Catalina unless the user installs a
# different distribution of Python.
#
# The executable created by shiv needs at least Python 3.6 because it uses
# f-strings internally.  If you try to run the shiv-produced result with an
# earlier version of Python, you get a syntax error and you have to be a
# Python expert to figure out what it means (namely, that your version of
# Python is too low).  There is no provision in shiv to do something like
# test the minimum version of Python in its bootstrap script, so if we want to
# give the user better information about why it fails on Python versions before
# 3.6, we have to find another solution.
#
# The approach used here is to leverage shiv's option to include a custom
# hash-bang line, and use that to insert a short polyglot script that tests
# the version of Python and either exits with an error or execs Python on the
# whole file.  This becomes the first few lines inside the eprints2archives
# zipapp.  The syntax for making this work is partly based on the 2016-03-02
# Stack Overflow posting at https://stackoverflow.com/a/35744488/743730.
#
# (Implementation note: the length of this hash-bang script is at the maximum
# character length accepted by shiv -- anything longer is rejected.  I would
# have wanted to echo a better error message but it's not possible.)

_HASHBANG_VERSION_TEST_FMT = r"""/bin/bash
''''test \$(python3 -V 2>&1|cut -c 10) -eq {0} && exec python3 -x \"\$0\" \"\$@\" # '''
''''exec echo 'Python != 3.{0}' # '''"""


# The following text is written into the zip file.

_ZIP_COMMENTS_FMT = '''
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This Zip archive file was created on {0}. It includes
a self-contained, executable copy of eprints2archives for
for Python version {2} on {3} systems. To learn more
about eprints2archives, please visit the following website:
https://github.com/caltechlibrary/eprints2archives/.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

'''

# The following text is written to a .txt file that is stored with the
# application in the zip file.  It gets extracted when users unzip the file
# and (hopefully) serves to orient users.

_README_FMT = '''
About the eprints2archives version {1} distribution for {3}
============================================================

The file named "eprints2archives" inside the ZIP file that
you downloaded is an executable Python program in a special
format (not a script) that only needs an installation of
Python version {2} on your computer to run.

Simply move or copy "eprints2archives" to a location where
you put other command-line programs on your computer.  A
popular location is /usr/local/bin/.  The following is an
example command that you can type in a terminal to move
"eprints2archives" there:

    sudo mv eprints2archives /usr/local/bin

To see usage information for "eprints2archives", run it
with the -h option, like this:

    eprints2archives -h

For more detailed help, particularly for how to install
credentials to use cloud services from Amazon, Google,
and Microsoft, please visit the website

    https://github.com/caltechlibrary/eprints2archives

Thank you for your interest in eprints2archives!

Mike Hucka
california institute of Technology Library
{0}
'''


# Utility functions used below.
# .............................................................................

usage = 'Usage: create-pyz outputdir pythonversion'

def run(cmd, quiet = False):
    if quiet:
        return check_output(cmd, shell = True).decode()
    else:
        return check_call(cmd, shell = True,
                          stdout = sys.stdout, stderr = subprocess.STDOUT)


def quit(msg):
    Console().print(f'‼️  {msg}', style = "bold red")
    Console().print(f'{usage}', style = "yellow")
    exit(1)


def inform(text):
    Console().print(text, style = "cyan")


# Sanity-check the run-time environment before attempting anything else.
# .............................................................................

here       = getcwd()
req_file   = join(here, 'requirements.txt')
setup_file = join(here, 'setup.cfg')

if not exists(req_file):
    quit(f'Expected to be in same directory as requirements.txt')

if not exists(setup_file):
    quit(f'setup.cfg does not exist in {here}')

if len(sys.argv) < 2:
    quit(f'First argument must be destination where outputs will be written')

dest = sys.argv[1]

if not exists(dest):
    quit(f'Directory does not exist: {dest}')

if len(sys.argv) < 3:
    quit(f'Second argument must be the target Python version')

py_version = sys.argv[2]
py_minor_version = py_version.split('.')[1]

if len(py_version.split('.')) < 3 or not all(isint(x) for x in py_version.split('.')):
    quit(f'Python version must be in the form x.y.z')

known_versions = [s.strip() for s in run('pyenv versions', True).split('\n')]
if py_version not in known_versions:
    quit(f'pyenv lacks version {py_version} -- run "pyenv install {py_version}"')

if int(py_minor_version) < 6:
    quit(f'The minimum Python version is 3.6')


# Gather information.
# .............................................................................

py_short_version = '.'.join(py_version.split('.')[0:2])

with open('setup.cfg', 'r') as config_file:
    for line in config_file.readlines():
        if line.startswith('version'):
            h_version = line.split('=')[1].strip()

os      = run("uname -s | tr '[A-Z]' '[a-z]' | sed 's/darwin/macos/'", True).strip()
dirname = f'eprints2archives-{h_version}-{os}-python{py_short_version}'
outdir  = join(dest, dirname)
outname = f'eprints2archives'
today   = str(date.today())


# Do the work.
# .............................................................................

inform(f'Creating output directory in {outdir}')
run(f'rm -rf {outdir}')
run(f'mkdir -p {outdir}')
chdir(outdir)

inform(f'Setting up pyenv local environment')
run(f'pyenv local {py_version}')
run(f'~/.pyenv/shims/pip install --no-cache-dir --force-reinstall -r {req_file}')
run(f'~/.pyenv/shims/pip install --no-cache-dir --force-reinstall shiv --upgrade')

inform(f'Building output with shiv')

hashbang = _HASHBANG_VERSION_TEST_FMT.format(py_minor_version)
run(f'~/.pyenv/shims/shiv -p "{hashbang}" -c eprints2archives -o "{outname}" -E '
    + f'--prefer-binary eprints2archives=={h_version}')

inform(f'Creating zip file')
zip_file = dirname + '.zip'
comment  = _ZIP_COMMENTS_FMT.format(today, h_version, py_short_version, os)
readme   = _README_FMT.format(today, h_version, py_version, os)
with zipfile.ZipFile(zip_file, 'w', ZIP_STORED) as zf:
    zf.write(outname, join(dirname, outname))
    zf.writestr(join(dirname, 'README-EPRINTS2ARCHIVES-INSTRUCTIONS.txt'), readme)
    zf.comment = comment.encode()

inform(f'Done; output is in {outdir}')
